### ISSUE TITLE
Add statement that resource groups are not supported

### ISSUE THREAD

**Issue by mbirch-ca** [IBM-Bluemix-Docs/Registry#363]
While its clear based on the documentation about how to limit access to the container registry by namespace in the following section:

  https://cloud.ibm.com/docs/services/Registry?topic=registry-iam#access_roles_using

It does not mention that resource groups are not supported by the container registry.   It would have helped to have that information as a note.

**Comment by artberger** [comment]
@mbirch-ca thanks again for your feedback. I've updated the docs with a note about the resource group limitation in a couple places including there. Closing.
